http: add missing header
httpserver.cpp:71:10: error: ‘deque’ in namespace ‘std’ does not name a template type
   71 |     std::deque<std::unique_ptr<WorkItem>> queue;
      |          ^~~~~